### PR TITLE
fix(worker): Add tmp shard cleanup on indexing failure

### LINKED ISSUE #804: [bug] Left over indexing shards are filling up the disk slowly
We have about 300gb allocated to sourcebot, and normally it only takes up 100gb of storage. But we have noticed that there are a lot of .tmp zoekt shards that are left behind that slowly take over more and more space. 
The ID on these temp files matches with the repo ID that constantly fail to index.
Here is a chart to show you what we are seeing. 
We have created a clean up script that we have to run from time to time. 

We have a bunch of large repos that zoekt has never been able to index. Which I suspect might be causing this?

Image

Here is an error log that I frequently see. (Also quick aside, whenever the zoekt indexer throws an error the node process gets killed, which cause the next app to restart. Minor inconvenience)

```
stack:  Error: Command failed: zoekt-git-index -allow_missing_branches -index /data/.sourcebot/index -max_trigram_count 50000 -file_limit 2097152 -branches "HEAD" -tenant_id 1 -repo_id 1618 -shard_prefix 1_1618 -large_file "..." /data/.sourcebot/repos/1618 
2026/01/28 16:11:14 attempting to index 6560 total files 
2026/01/28 16:11:28 symbol analysis finished for shard statistics: duration=1s symbols=1 bytes=105038110 
at genericNodeError (node:internal/errors:985:15) 
at wrappedFn (node:internal/errors:539:14) 
at ChildProcess.exithandler (node:child_process:417:12) 
at ChildProcess.emit (node:events:508:28) 
at maybeClose (node:internal/child_process:1101:16) 
at Socket.<anonymous> (node:internal/child_process:457:11) 
at Socket.emit (node:events:508:28) 
at Pipe.<anonymous> (node:net:346:12)

```

### PR DESCRIPTION
**Pull request by msukkari**
Clean up temporary Zoekt shard files on indexing failure to prevent disk space exhaustion.

When `zoekt-git-index` fails during repository indexing, it leaves behind `.tmp` shard files. These accumulate over time, especially for repos that repeatedly fail to index, leading to disk space issues. This PR adds logic to automatically remove these temporary files immediately after an indexing operation fails.

Fixes #804

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed issue where temporary files created during index operations were not being cleaned up when failures occurred, which could accumulate and consume unnecessary disk space.

### CODE REVIEW

File: packages/backend/src/repoIndexManager.ts [hunk 1]
```diff
@@ -438,9 +438,17 @@ export class RepoIndexManager {
         }
 
         logger.info(`Indexing ${repo.name} (id: ${repo.id})...`);
-        const { durationMs } = await measure(() => indexGitRepository(repo, this.settings, revisions, signal));
-        const indexDuration_s = durationMs / 1000;
-        logger.info(`Indexed ${repo.name} (id: ${repo.id}) in ${indexDuration_s}s`);
+        try {
+            const { durationMs } = await measure(() => indexGitRepository(repo, this.settings, revisions, signal));
+            const indexDuration_s = durationMs / 1000;
+            logger.info(`Indexed ${repo.name} (id: ${repo.id}) in ${indexDuration_s}s`);
```
Comment (brendan-kellam) [inline packages/backend/src/repoIndexManager.ts:483]: I think this is a fair workaround and we should probably have a mechanism for cleaning up these files, but it doesn't really address the root cause for why these files are being created in the first place.
