### PR TITLE
fix(web): Document 403 errors with user driven permission syncing when scope changes occur

### LINKED ISSUE #638: [bug] User driven permission syncing will fail with 403 Unauthorized for accounts created before permission syncing was enabled
### Describe the bug

We only request the `read_api` (or `repo`) scope to accounts when permission syncing is enabled, meaning if a account is created **before** permission syncing is enabled, user driven permission sync jobs for that account will fail with the following error:

```
[worker] 2025-11-28T19:48:24.132Z info: [user-permission-syncer:job:cmij9z3x90002xnti61r6kjui] Syncing permissions for gitlab account (id: cmij9t22n0004xn64szkd3hxs) for user brendan@sourcebot.dev...
[worker] 2025-11-28T19:48:24.462Z error: [gitlab] Failed to fetch projects for authenticated user. Forbidden
[worker] GitbeakerRequestError: Forbidden
[worker]     at throwFailedRequestError (file:///Users/brendan/sourcebot/node_modules/@gitbeaker/rest/dist/index.mjs:41:9)
[worker]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[worker]     at async defaultRequestHandler (file:///Users/brendan/sourcebot/node_modules/@gitbeaker/rest/dist/index.mjs:74:48)
[worker]     at async file:///Users/brendan/sourcebot/node_modules/@gitbeaker/core/dist/index.mjs:99:22
[worker]     at async fetchWithRetry (file:///Users/brendan/sourcebot/packages/backend/dist/utils.js:69:20)
[worker]     at async getProjectsForAuthenticatedUser (file:///Users/brendan/sourcebot/packages/backend/dist/gitlab.js:266:26)
[worker]     at async file:///Users/brendan/sourcebot/packages/backend/dist/ee/accountPermissionSyncer.js:168:47
[worker]     at async AccountPermissionSyncer.runJob (file:///Users/brendan/sourcebot/packages/backend/dist/ee/accountPermissionSyncer.js:132:25)
[worker]     at async /Users/brendan/sourcebot/node_modules/bullmq/dist/cjs/classes/worker.js:517:32
[worker]     at async Worker.retryIfFailed (/Users/brendan/sourcebot/node_modules/bullmq/dist/cjs/classes/worker.js:742:24)
[worker] 2025-11-28T19:48:24.479Z error: [user-permission-syncer:job:cmij9z3x90002xnti61r6kjui] Account permission sync job failed for account (id: cmij9t22n0004xn64szkd3hxs) for user brendan@sourcebot.dev: Forbidden
```

### To reproduce

1. With permission syncing disabled, create a new Sourcebot user with either GitHub or GitLab idp
2. Shutdown, enable permission syncing, and restart
3. Notice that the user permission sync jobs will fail with 403s.

### Sourcebot deployment information

Sourcebot version (e.g. v3.0.1): v4.10.0

### Additional information

We probably need to re-create the access token after permission syncing is enabled.

### PR DESCRIPTION
**Pull request by brendan-kellam**
Ramble / context: user driven permission syncing uses the `access_token` stored on the `Account` object that is acquired when the user signs in with GitHub/GitLab/whatever. Access tokens have a associated scopes (e.g., `read:user`, `repo`, etc.). For permission syncing, we require additional oauth scopes from the base ones we usually request.

When enabling permission syncing on a existing deployment, this will result in 403 errors since the existing oauth scopes are insufficient for the api requests we are making. Signing out of the account and re-signing in resolves the issue since the new oauth scopes will be requested.

This PR originally attempted to automate the process by automatically signing out the account when the scopes changed, but this was deemed to be too complicated and fragile. Instead, I've added improved error messages and documanted the issue in the docs.

Fixes #638 
Fixes SOU-98

---

> [!NOTE]
> Improves reliability and clarity of user-driven permission syncing by validating OAuth scopes and ensuring refreshed tokens are stored.
> 
> - Backend: In `accountPermissionSyncer`, fetch and validate OAuth scopes (`repo` for GitHub, `read_api` for GitLab) via new helpers (`getOAuthScopesForAuthenticatedUser` in `github.ts`/`gitlab.ts`); throw explicit errors and prompt re-auth when tokens/scopes are insufficient. 
> - Web auth: On `signIn` event, explicitly update `Account` with latest OAuth token fields to persist refreshed credentials.
> - Docs: Add warning to `permission-syncing.mdx` explaining scope-related errors when enabling on existing deployments and the need to re-authenticate.
> - Changelog: Notes improved error messaging for OAuth scope issues.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 13c4c9cb2a380f4fd602c17fbef5488328305c71. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/web/src/app/components/authMethodSelector.tsx [hunk 1]
```diff
@@ -29,9 +29,20 @@ export const AuthMethodSelector = ({
         // Call the optional analytics callback first
         onProviderClick?.(provider);
 
-        signIn(provider, {
-            redirectTo: callbackUrl ?? "/"
-        });
+        // @nocheckin
```
Comment (brendan-kellam) [inline packages/web/src/app/components/authMethodSelector.tsx]: nocheckin

**Comment by brendan-kellam** [comment]
test
