### PR TITLE
fix(web): Ask sourcebot perf improvements

### LINKED ISSUE #626: [bug] Ask Sourcebot chat runs into bottleneck client-side, causing webpage crash
### Describe the bug

Hello,

I notice that when using Ask Sourcebot on my self-hosted instance, I see the chat rendering getting slower as the response grows in size, to the point where browser becomes unresponsive. In the worst case, the browser crashed with a STATUS_ACCESS_VIOLATION error. 

I’m guessing the culprit is in the `ChatThread` `useChat`/`messagePairs` hook, which seems to re-render the component (and all message pairs) on every chunk received. Maybe some memoization would help? And/or batching some of the heavy rendering work.

https://github.com/sourcebot-dev/sourcebot/blob/main/packages/web/src/features/chat/components/chatThread/chatThread.tsx#L313

### To reproduce

self-hosted instance with an internal LLM 

### Sourcebot deployment information

Sourcebot version (e.g. v3.0.1): 
running on sourcebot:main.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brendan-kellam**
Improves Ask mode performance by adding memoization in various places + some other optimizations

Fixes #626

### CODE REVIEW

File: packages/web/src/features/chat/components/chatThread/chatThread.tsx [hunk 1]
```diff
@@ -196,46 +189,47 @@ export const ChatThread = ({
         hasSubmittedInputMessage.current = true;
     }, [inputMessage, sendMessage]);
 
+    // @todo: this need to be optimized to avoid excessive re-renders
```
Comment (brendan-kellam) [inline packages/web/src/features/chat/components/chatThread/chatThread.tsx]: todo

File: packages/web/src/features/chat/components/chatThread/referencedFileSourceListItem.tsx [hunk 2]
```diff
@@ -124,6 +122,8 @@ const ReferencedFileSourceListItem = ({
         return createCodeFoldingExtension(references, 3);
     }, [references]);
 
+    // console.log(`re-renderign for file ${fileName}`);
```
Comment (brendan-kellam) [inline packages/web/src/features/chat/components/chatThread/referencedFileSourceListItem.tsx]: remove

**Comment by brendan-kellam** [comment]
@coderabbitai A user has raised that they are hitting a 404 error when getting redirected to localhost:3000/~/chat/<some hash>. I believe this is a regression that was introduced in this PR. Please find the issue.

**Comment by brendan-kellam** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> 🧩 Analysis chain
> 🏁 Script executed:
> 
> ```
> #!/bin/bash
> # Get the details of PR #632 including files changed
> gh pr view 632 --json files,title,body --jq '.files[] | .path'
> ```
> 
> Length of output: 1589
> 
> 🏁 Script executed:
> 
> ```
> #!/bin/bash
> # Get the diff for PR #632 to see what was changed
> gh pr diff 632
> ```
> 
> Length of output: 87353
> 
> @brendan-kellam I found the regression! The issue is that several client-side navigation calls were changed to use the hardcoded `SINGLE_TENANT_ORG_DOMAIN` constant (which is `~`) instead of the actual domain from `useDomain()` hook.
> 
> ## Root Cause
> The Next.js app structure uses `[domain]` as a dynamic route parameter (e.g., `app/[domain]/chat/[id]/page.tsx`). When users navigate to chat routes, the code now redirects to `/~/chat/<hash>` instead of using the user's actual domain, causing a 404 error.
> 
> ## Affected Files
> **1. `packages/web/src/features/chat/useCreateNewChatThread.ts`** (Lines 49-50)
> 
> ```ts
> // BEFORE (correct):
> const url = createPathWithQueryParams(`/${domain}/chat/${response.id}`);
> 
> // AFTER (broken):
> const url = createPathWithQueryParams(`/${SINGLE_TENANT_ORG_DOMAIN}/chat/${response.id}`);
> ```
> 
> **2. `packages/web/src/app/[domain]/chat/components/chatSidePanel.tsx`** (Lines 106, 133, 147, 165)
> 
> ```ts
> // Multiple instances where navigation now uses SINGLE_TENANT_ORG_DOMAIN:
> router.push(`/${SINGLE_TENANT_ORG_DOMAIN}/chat`);
> router.push(`/${SINGLE_TENANT_ORG_DOMAIN}/chat/${chat.id}`);
> ```
> 
> **3. `packages/web/src/features/chat/components/chatThread/markdownRenderer.tsx`** (Line 179)
> 
> ```ts
> const url = createPathWithQueryParams(`/${SINGLE_TENANT_ORG_DOMAIN}/search`, ...);
> ```
> 
> **4. `packages/web/src/features/chat/components/chatThread/tools/searchCodeToolComponent.tsx`** (Line 80)
> 
> ```ts
> href={createPathWithQueryParams(`/${SINGLE_TENANT_ORG_DOMAIN}/search`, ...)}
> ```
> 
> **5. `packages/web/src/features/chat/components/chatThread/tools/shared.tsx`** (Line 29)
> 
> ```ts
> domain: SINGLE_TENANT_ORG_DOMAIN,
> ```
> 
> ## Solution
> These files need to be reverted to use `useDomain()` hook for client-side navigation. The `SINGLE_TENANT_ORG_DOMAIN` constant should only be used on the server-side where the domain context is guaranteed, not for client-side routing where the actual domain may vary.
> 
> Would you like me to create an issue to track this fix?

@coderabbitai this is not the issue.
